version: '3.0'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: example_db
  app:
    image: app
    build:
      dockerfile: DockerFile
    container_name: application
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: userdb
      SPRING_DATASOURCE_PASSWORD: passworddb
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/example_db